[package]
name = "tapciify"
version = "1.0.0"

edition = "2021"
readme = "README.md"
authors = ["Alexiy Rybin <alexiy.rybin@gmail.com>"]
repository = "https://github.com/tapnisu/tapciify/"
description = "CLI tool that can let you view images/videos in terminal as ASCII"
keywords = ["image", "ascii", "terminal", "cli"]
categories = [
    "command-line-utilities",
    "multimedia",
    "multimedia::images",
    "multimedia::video",
    "visualization",
]
license = "MIT"

[dependencies]
clap = { version = "4.2.5", features = ["derive"] }
colored = "2.0.0"
crossterm = "0.26.1"
glob = "0.3.1"
image = "0.24.6"
indicatif = "0.17.3"
rayon = "1.7.0"
