[package]
name = "tapciify"
version = "2.0.0"
edition = "2021"
readme = "README.md"
authors = ["Aleksei Rybin <0xalekseirybin@gmail.com>"]
repository = "https://github.com/tapciify/tapciify/"
description = "CLI tool that can let you view images in terminal as ASCII art"
keywords = ["image", "ascii", "terminal", "cli"]
categories = [
    "command-line-utilities",
    "multimedia",
    "multimedia::images",
    "multimedia::video",
    "visualization",
]
license = "MIT"

[dependencies]
clap = { version = "4", features = ["derive"], optional = true }
colored = "2"
crossterm = { version = "0.27", optional = true }
image = "0.24"
indicatif = { version = "0.17", optional = true }
rayon = { version = "1", optional = true }

[target.'cfg(windows)'.dependencies]
glob = "0.3"

[features]
default = ["full"]
full = ["parallelism", "player"]
parallelism = ["dep:rayon"]
player = ["dep:clap", "dep:crossterm", "dep:indicatif"]

[[bin]]
name = "tapciify"
required-features = ["player"]
