[package]
name = "tapciify"
version = "0.2.2"
edition = "2021"
readme = "README.md"
authors = ["Alexiy Rybin <alexiy.rybin@gmail.com>"]
repository = "https://github.com/tapnisu/tapciify/"
license = "MIT"

[dependencies]
clap = { version = "4.0.14", features = ["derive"] }
colored = "2.0.0"
crossterm = "0.25.0"
image = "0.24.3"
