[package]
name = "tapciify"
version = "2.0.0"
edition = "2021"
readme = "README.md"
authors = ["Alexiy Rybin <alexiy.rybin@gmail.com>"]
repository = "https://github.com/tapnisu/tapciify/"
description = "CLI tool that can let you view images/videos in terminal as ASCII"
keywords = ["image", "ascii", "terminal", "cli"]
categories = [
    "command-line-utilities",
    "multimedia",
    "multimedia::images",
    "multimedia::video",
    "visualization",
]
license = "MIT"

[features]
default = ["full"]
full = ["player", "parallelism"]
player = []
parallelism = []

[dependencies]
clap = { version = "4", features = ["derive"] }
colored = "2"
crossterm = "0.26"
image = "0.24"
indicatif = "0.17"
rayon = "1"

[target.'cfg(windows)'.dependencies]
glob = "0.3"
