[package]
name = "tapciify"
version = "3.1.0"
edition = "2021"
readme = "README.md"
authors = ["Aleksei Rybin <0xalekseirybin@gmail.com>"]
repository = "https://github.com/tapciify/tapciify/"
description = "CLI tool that can let you view images in terminal as ASCII art"
keywords = ["image", "ascii", "terminal", "cli"]
categories = [
    "command-line-utilities",
    "multimedia",
    "multimedia::images",
    "multimedia::video",
    "visualization",
]
license = "MIT"

[dependencies]
colored = "2"
image = "0.24"
err-derive = "0.3"

clap = { version = "4", features = ["derive"], optional = true }
crossterm = { version = "0.27", optional = true }
glob = { version = "0.3", optional = true }
indicatif = { version = "0.17", optional = true }
rayon = { version = "1", optional = true }

[features]
default = ["full"]
full = ["rayon", "player"]

parallelism = ["dep:rayon"]
multithreading = ["dep:rayon"]
rayon = ["dep:rayon"]

player = ["dep:clap", "dep:crossterm", "dep:indicatif", "dep:glob"]

[[bin]]
name = "tapciify"
required-features = ["player"]
