[package]
name = "tapciify"
version = "0.5.0"

edition = "2021"
readme = "README.md"
authors = ["Alexiy Rybin <alexiy.rybin@gmail.com>"]
repository = "https://github.com/tapnisu/tapciify/"
description = "CLI tool that can let you view images in terminal"
keywords = ["image", "ascii", "terminal", "cli"]
categories = ["command-line-utilities", "multimedia", "multimedia::images", "multimedia::video", "visualization"]
license = "MIT"

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
colored = "2.0.0"
crossterm = "0.26.0"
image = "0.24.5"
tokio = { version = "1.25.0", features = ["full"] }
indicatif = "0.17.3"
