name: CI

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.2.0
      - name: cargo install cargo-audit
        run: cargo install cargo-audit
      - name: Build
        run: cargo build --verbose
      - name: Build with no default features
        run: cargo build --no-default-features
      - name: Build with no default features
        run: cargo build --no-default-features -F player
      - name: Run tests
        run: cargo test --verbose
      - name: Clippy
        run: cargo clippy --verbose
      - name: Audit
        run: cargo audit
